version: '2.1'
orbs:
  matlab: mathworks/matlab@1

executors:
  linux:
    machine:
      image: ubuntu-2204:current
  windows:
    resource_class: windows.medium
    machine:
      image: windows-server-2022-gui:current  
jobs:
  build:
    parameters:
      os:
        type: executor
    executor: << parameters.os >> 
    steps:
      - checkout
      - matlab/install:
          release: latest-including-prerelease
      - matlab/run-build:
          tasks: test

workflows:
  tests-on-all-platforms:
    jobs:
      - build:
          matrix:
            parameters:
              os: [linux, macos, windows]
