version: '2.1'
orbs:
  matlab: mathworks/matlab@1

executors:
  linux:
    machine:
      image: ubuntu-2204:current
  windows:
    resource_class: windows.medium
    machine:
      image: windows-server-2022-gui:current  

jobs:
  build:
    parameters:
      os:
        type: executor
      command:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout
      - matlab/install:
          release: latest
      - matlab/run-command:
          command: << parameters.command >>

workflows:
  tests-on-all-platforms:
    jobs:
      - build:
          name: build-linux
          os: linux
          command: disp('hello linux')
      - build:
          name: build-windows
          os: windows
          command: disp('hello windows')
