on: [push]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        release: [latest, r2023a]
    name: Run MATLAB Build
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v3
        with:
          cache: true
          release: ${{ matrix.release }}
      - name: BOOM
        uses: davidbuzinski/run-command@main
        with:
          command: error("BOOM!");
      #   
      - name: Run tests
        uses: davidbuzinski/run-command@main
        with:
          command: addpath(genpath("hedcode")), addpath(genpath("tests"), runAllTests
